# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
   branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Test API
      working-directory: mongoApi
      run: |
        npm install
        echo 'Finished install'
        npm run start:test
        echo 'Started server'
        npm test
      
    - name: Wait a bit for server spool-up
      uses: jakejarvis/wait-action@master
      with:
        time: '5s' 
        
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: angularClient
        start: npm start
        # quote the url to be safe against YML parsing surprises
        wait-on: 'http://localhost:4200'
        
    #- name: Run Cypress Front
     # working-directory: angularClient
     # run: |
     #   echo 'npm install'
     #   npm install
     #   echo 'npm install finished'
     #   echo 'npm cypress-silent'
     #   npm cypress-silent
     #   echo 'npm cypress-silent finished'
